### ISSUE TITLE
Error in running problem1.py

### ISSUE THREAD

**Issue by janismdhanbad** [Auquan/quant-quest-2#1]
Hi, please review this error:

```
Traceback (most recent call last):
  File "problem1.py", line 142, in <module>
    tradingSystem.startTrading(onlyAnalyze=False, shouldPlot=False)
  File "C:\Temp\Anaconda\lib\site-packages\backtester\trading_system.py", line 131, in startTrading
    self.initialize()
  File "C:\Temp\Anaconda\lib\site-packages\backtester\trading_system.py", line 123, in initialize
    self.dataParser = self.tsParams.getDataParser()
  File "C:\Temp\Anaconda\lib\site-packages\backtester\sample_scripts\fair_value_params.py", line 29, in getDataParser
    instrumentIds=instrumentIds)
  File "C:\Temp\Anaconda\lib\site-packages\backtester\dataSource\quant_quest_data_source.py", line 27, in __init__
    self.ensureAllInstrumentsFile(dataSetId)
  File "C:\Temp\Anaconda\lib\site-packages\backtester\dataSource\quant_quest_data_source.py", line 50, in ensureAllInstrumentsFile
    response = urlopen(url)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by chandinijain** [comment]
SampleData is no longer available. Please use trainingData1 or trainingData2 or trainingData3.
Change this function in problem1.py
```
def getTrainingDataSet(self):
        return "trainingData1"
```


On Sep 16, 2017 5:47 PM, "Janpreet Singh" <notifications@github.com> wrote:

Hi, please review this error:

Traceback (most recent call last):
  File "problem1.py", line 142, in <module>
    tradingSystem.startTrading(onlyAnalyze=False, shouldPlot=False)
  File "C:\Temp\Anaconda\lib\site-packages\backtester\trading_system.py",
line 131, in startTrading
    self.initialize()
  File "C:\Temp\Anaconda\lib\site-packages\backtester\trading_system.py",
line 123, in initialize
    self.dataParser = self.tsParams.getDataParser()
  File "C:\Temp\Anaconda\lib\site-packages\backtester\sample_scripts\fair_value_params.py",
line 29, in getDataParser
    instrumentIds=instrumentIds)
  File "C:\Temp\Anaconda\lib\site-packages\backtester\dataSource\quant_quest_data_source.py",
line 27, in __init__
    self.ensureAllInstrumentsFile(dataSetId)
  File "C:\Temp\Anaconda\lib\site-packages\backtester\dataSource\quant_quest_data_source.py",
line 50, in ensureAllInstrumentsFile
    response = urlopen(url)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Temp\Anaconda\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Auquan/quant-quest-2/issues/1>, or mute the thread
